# Usa una imagen base oficial reciente
FROM node:22-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia archivos de dependencias
COPY package*.json ./

# Instala TODAS las dependencias (incluye dev)
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto del backend
EXPOSE 3500

# Comando por defecto
CMD ["npm", "run", "dev"]